import { Ubuntu_Mono } from "next/font/google";
import "./globals.css";

// Components
import { Header } from "@/components/Header";
import PageTransition from "@/components/PageTransition";
const ubuntuMono = Ubuntu_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-ubuntuMono",
});

export const metadata = {
  title: "Karhacter",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="vi-en">
      <body className={ubuntuMono.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
